-- BU KODU SUPABASE SQL EDITOR KISMINA YAPIŞTIRIP "RUN" TUŞUNA BASINIZ

-- 7. Malzemeler Tablosu
create table public.materials (
  id bigint generated by default as identity primary key,
  category text not null, -- 'pump', 'motor', 'power_unit', 'accessory', 'cylinder_pricing', 'burst_valve', 'main_valve', 'hose'
  name text not null,
  price numeric default 0,
  properties jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. RLS Politikaları (Malzemeler için)
alter table public.materials enable row level security;
create policy "Enable read access for all users" on public.materials for select using (true);
create policy "Enable insert access for all users" on public.materials for insert with check (true);
create policy "Enable update access for all users" on public.materials for update using (true);
create policy "Enable delete access for all users" on public.materials for delete using (true);

-- 9. Varsayılan Verileri Yükle (data.js içeriğinden dönüştürüldü)

-- PUMPS
insert into public.materials (category, name, price, properties) values
('pump', 'PAVE020#4J', 163.45, '{"flow": 7.80}'),
('pump', 'PAVE020#4B', 163.45, '{"flow": 11.90}'),
('pump', 'PAVE025#4K', 163.45, '{"flow": 15.70}'),
('pump', 'PAVE025#4J', 163.60, '{"flow": 18.10}'),
('pump', 'PAVE025#4A', 163.45, '{"flow": 21.70}'),
('pump', 'PAVE025#4B', 163.60, '{"flow": 26.00}'),
('pump', 'PA025#6C', 163.60, '{"flow": 33.40}'),
('pump', 'PA025#6A', 163.60, '{"flow": 38.00}'),
('pump', 'PA029#6B', 163.60, '{"flow": 45.60}'),
('pump', 'PA032#4A', 163.54, '{"flow": 53.70}'),
('pump', 'PA032#4B', 163.54, '{"flow": 71.60}'),
('pump', 'PAP040#4A', 163.48, '{"flow": 98.90}'),
('pump', 'PAP040#4B', 163.48, '{"flow": 121.00}'),
('pump', 'PAP040#4C', 163.48, '{"flow": 145.30}'),
('pump', 'PAP045#4A', 225.58, '{"flow": 177.90}'),
('pump', 'PAP045#4B', 225.58, '{"flow": 210.50}'),
('pump', 'PAP045#4C', 225.58, '{"flow": 247.40}'),
('pump', 'PAP055#4A', 225.58, '{"flow": 252.60}'),
('pump', 'PAP055#4B', 305.89, '{"flow": 302.10}'),
('pump', 'PAP055#4C', 305.89, '{"flow": 358.90}'),
('pump', 'PAP055#4D', 305.89, '{"flow": 376.80}'),
('pump', 'PAP060#4A', 417.07, '{"flow": 429.50}'),
('pump', 'PAP060#4B', 417.07, '{"flow": 525.30}'),
('pump', 'PAP072#4A', 655.33, '{"flow": 615.80}'),
('pump', 'PAP072#4B', 655.33, '{"flow": 727.40}'),
('pump', 'PAP072#4C', 655.33, '{"flow": 872.60}'),
('pump', 'PAP060#4B', 655.33, '{"flow": 1150.60}');

-- MOTORS
insert into public.materials (category, name, price, properties) values
('motor', 'SBBL64', 236.93, '{"kw": 2.2}'),
('motor', 'SBBL100', 236.29, '{"kw": 2.9}'),
('motor', 'SBBL153', 240.41, '{"kw": 4.7}'),
('motor', 'SBBL163', 255.97, '{"kw": 5.8}'),
('motor', 'SBBL173', 275.95, '{"kw": 7.7}'),
('motor', 'SBBL183', 312.50, '{"kw": 9.5}'),
('motor', 'SBBL193', 316.73, '{"kw": 11.0}'),
('motor', 'SBBL203', 349.25, '{"kw": 12.5}'),
('motor', 'SBBL253', 362.52, '{"kw": 14.7}'),
('motor', 'SBBL263', 423.18, '{"kw": 18.4}'),
('motor', 'SBBL275', 468.17, '{"kw": 22.0}'),
('motor', 'SBBL212', 525.60, '{"kw": 24.0}'),
('motor', 'SBBL413', 617.09, '{"kw": 29.4}'),
('motor', 'SBBL423', 817.17, '{"kw": 36.8}'),
('motor', 'SBBL433', 867.55, '{"kw": 44.1}'),
('motor', 'SBBL313', 980.53, '{"kw": 51.5}'),
('motor', 'SBBL323', 1140.26, '{"kw": 58.8}'),
('motor', 'SBBL333', 1380.89, '{"kw": 73.5}');

-- POWER UNITS
insert into public.materials (category, name, price, properties) values
('power_unit', 'BTD-55', 400, '{"pumpMin": 8, "pumpMax": 25, "tankCapacity": 55}'),
('power_unit', 'BTS-75', 400, '{"pumpMin": 25, "pumpMax": 75, "tankCapacity": 75}'),
('power_unit', 'BTS-150', 600, '{"pumpMin": 75, "pumpMax": 150, "tankCapacity": 150}'),
('power_unit', 'BTS-250', 700, '{"pumpMin": 150, "pumpMax": 250, "tankCapacity": 250}'),
('power_unit', 'BTS-400', 950, '{"pumpMin": 240, "pumpMax": 380, "tankCapacity": 400}'),
('power_unit', 'BTS-600', 1150, '{"pumpMin": 380, "pumpMax": 500, "tankCapacity": 600}'),
('power_unit', 'BTS-1000', 1350, '{"pumpMin": 500, "pumpMax": 1000, "tankCapacity": 1000}'),
('power_unit', 'BTS-1800', 2250, '{"pumpMin": 500, "pumpMax": 1200, "tankCapacity": 1800}');

-- ACCESSORIES
insert into public.materials (category, name, price, properties) values
('accessory', 'Kompanse Klavuzu CX', 89, '{"category": "Kontrol"}'),
('accessory', 'El Pompası', 105, '{"category": "Güvenlik"}'),
('accessory', 'Küresel Vana BG', 0, '{"category": "Vana", "note": "Dynamic pricing"}'),
('accessory', 'Tank Isıtıcı 25°C', 197, '{"category": "Isıtma"}'),
('accessory', 'Y.Basınç Şalteri 10-100 Bar', 32, '{"category": "Güvenlik"}'),
('accessory', 'A.Basınç Şalteri 1-10 Bar', 32, '{"category": "Güvenlik"}'),
('accessory', 'Aşırı Yük', 32, '{"category": "Güvenlik"}'),
('accessory', 'Mikro Seviyeleme', 1150, '{"category": "Kontrol"}'),
('accessory', 'Güç Ünitesi Hortumları', 420, '{"category": "Bağlantı"}');

-- CYLINDER PRICING (Storing fixed/perMeter in properties)
insert into public.materials (category, name, price, properties) values
('cylinder_pricing', '50x0', 348.60, '{"perMeter": 62.77, "additional": 402.88}'),
('cylinder_pricing', '56x0', 363.09, '{"perMeter": 74.36, "additional": 407.62}'),
('cylinder_pricing', '60x0', 370.44, '{"perMeter": 87.09, "additional": 410.87}'),
('cylinder_pricing', '60x5', 319.26, '{"perMeter": 39.05, "additional": 381.19}'),
('cylinder_pricing', '63x0', 384.93, '{"perMeter": 91.62, "additional": 411.01}'),
('cylinder_pricing', '80x0', 462.35, '{"perMeter": 117.96, "additional": 449.04}'),
('cylinder_pricing', '80x5', 354.65, '{"perMeter": 52.36, "additional": 419.23}'),
('cylinder_pricing', '90x0', 480.74, '{"perMeter": 118.79, "additional": 474.69}'),
('cylinder_pricing', '90x5', 367.77, '{"perMeter": 62.26, "additional": 444.94}');
-- (Adding main ones as example, full list would be very long but fine)

-- MAIN VALVES
insert into public.materials (category, name, price) values
('main_valve', '0,5'' GV', 112.035),
('main_valve', '0,5'' KV1P', 254.647),
('main_valve', '0,5'' KV1S', 288.804),
('main_valve', '0,5'' KV2P', 297.496),
('main_valve', '0,5'' KV2S', 328.461),
('main_valve', '0,75'' EVD', 434.660),
('main_valve', '0,75'' EV100', 397.848),
('main_valve', '1,5'' EV100', 507.985);

