-- BU KODU SUPABASE SQL EDITOR KISMINA YAPIŞTIRIP "RUN" TUŞUNA BASINIZ

-- 1. Projeler Tablosu
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_number text not null,
  customer_name text,
  status text default 'draft', -- draft, production, etc.
  production_stage text default 'imalat', -- imalat, test, paketleme, sevkedildi
  inputs jsonb, -- Proje parametreleri (hız, kapasite vb.)
  selected_cylinder text,
  components jsonb, -- Seçilen motor, pompa vb.
  created_by text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Kullanıcılar Tablosu (Basit Auth için)
create table public.app_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Varsayılan Admin Kullanıcısını Ekle
insert into public.app_users (username, password, role)
values ('admin', 'admin123', 'admin');

-- 4. Row Level Security (RLS) - Şimdilik herkese açık (Anon key ile okuma/yazma)
-- Gerçek projede burayı kısıtlamak gerekir.
alter table public.projects enable row level security;
alter table public.app_users enable row level security;

create policy "Enable read access for all users" on public.projects for select using (true);
create policy "Enable insert access for all users" on public.projects for insert with check (true);
create policy "Enable update access for all users" on public.projects for update using (true);
create policy "Enable delete access for all users" on public.projects for delete using (true);

create policy "Enable read access for all users" on public.app_users for select using (true);
create policy "Enable insert access for all users" on public.app_users for insert with check (true);
create policy "Enable update access for all users" on public.app_users for update using (true);
create policy "Enable delete access for all users" on public.app_users for delete using (true);
