-- BU KODU SUPABASE SQL EDITOR KISMINA YAPIŞTIRIP "RUN" TUŞUNA BASINIZ

-- 5. Üretim Logları Tablosu (Tarihçe ve Takip İçin)
create table public.production_logs (
  id bigint generated by default as identity primary key,
  project_number text not null,
  previous_stage text,
  new_stage text not null,
  changed_by text, -- İşlemi yapan kullanıcı
  notes text, -- Ek notlar (opsiyonel)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. RLS Politikaları (Log tablosu için)
alter table public.production_logs enable row level security;

create policy "Enable read access for all users" on public.production_logs for select using (true);
create policy "Enable insert access for all users" on public.production_logs for insert with check (true);
